version: '3.9'

services:
  nginx:
    image: nginx:1.23.2
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./project:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php/conf.d/php-fpm.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_project
      MYSQL_USER: phper
      MYSQL_PASSWORD: phper_p
    # command:
    #   mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
    ports:
      - 33306:3306

  administer:
    image: phpmyadmin/phpmyadmin
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=phper_p
    depends_on:
      - db
    ports:
      - 8083:80